package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/superduperpiyuxh/deoxy/internal/config"
)

var initCmd = &cobra.Command{
	Use:   "init [path]",
	Short: "Scaffold a .deoxy.yaml config file in the specified directory",
	Long: `Create a .deoxy.yaml configuration file with sensible defaults.

If no path is given, the config is created in the current directory.
The command will fail if .deoxy.yaml already exists.`,
	Args: cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		dir := "."
		if len(args) > 0 {
			dir = args[0]
		}

		// Ensure directory exists
		info, err := os.Stat(dir)
		if err != nil {
			return fmt.Errorf("cannot access %q: %w", dir, err)
		}
		if !info.IsDir() {
			return fmt.Errorf("%q is not a directory", dir)
		}

		path := filepath.Join(dir, ".deoxy.yaml")

		// Generate default config
		cfg := config.LoadDefaultConfig()
		data, err := cfg.MarshalYAML()
		if err != nil {
			return fmt.Errorf("marshaling default config: %w", err)
		}

		// Add a header comment
		content := "# deoxy configuration\n" +
			"# Generated by 'deoxy init'\n" +
			"# See https://github.com/superduperpiyuxh/deoxy for documentation\n" +
			string(data)

		// Create atomically with O_EXCL to prevent TOCTOU races
		f, err := os.OpenFile(path, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0644)
		if err != nil {
			if os.IsExist(err) {
				return fmt.Errorf("%s already exists", path)
			}
			return fmt.Errorf("creating %s: %w", path, err)
		}

		if _, err := f.Write([]byte(content)); err != nil {
			f.Close()
			os.Remove(path)
			return fmt.Errorf("writing %s: %w", path, err)
		}
		if err := f.Close(); err != nil {
			return fmt.Errorf("closing %s: %w", path, err)
		}

		fmt.Printf("Created %s\n", path)
		return nil
	},
}
